// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type BuildResponse struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=EmailAddress,proto3" json:"EmailAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{1}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type ReverseRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReverseRequest) Reset()         { *m = ReverseRequest{} }
func (m *ReverseRequest) String() string { return proto.CompactTextString(m) }
func (*ReverseRequest) ProtoMessage()    {}
func (*ReverseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{2}
}

func (m *ReverseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseRequest.Unmarshal(m, b)
}
func (m *ReverseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseRequest.Marshal(b, m, deterministic)
}
func (m *ReverseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseRequest.Merge(m, src)
}
func (m *ReverseRequest) XXX_Size() int {
	return xxx_messageInfo_ReverseRequest.Size(m)
}
func (m *ReverseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseRequest proto.InternalMessageInfo

func (m *ReverseRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ReverseResponse struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=EmailAddress,proto3" json:"EmailAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReverseResponse) Reset()         { *m = ReverseResponse{} }
func (m *ReverseResponse) String() string { return proto.CompactTextString(m) }
func (*ReverseResponse) ProtoMessage()    {}
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{3}
}

func (m *ReverseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseResponse.Unmarshal(m, b)
}
func (m *ReverseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseResponse.Marshal(b, m, deterministic)
}
func (m *ReverseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseResponse.Merge(m, src)
}
func (m *ReverseResponse) XXX_Size() int {
	return xxx_messageInfo_ReverseResponse.Size(m)
}
func (m *ReverseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseResponse proto.InternalMessageInfo

func (m *ReverseResponse) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildRequest)(nil), "proto.BuildRequest")
	proto.RegisterType((*BuildResponse)(nil), "proto.BuildResponse")
	proto.RegisterType((*ReverseRequest)(nil), "proto.ReverseRequest")
	proto.RegisterType((*ReverseResponse)(nil), "proto.ReverseResponse")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x4d, 0xcc,
	0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x2a, 0x5c, 0x3c, 0x4e,
	0xa5, 0x99, 0x39, 0x29, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0xae,
	0x20, 0x55, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x92, 0x31, 0x17, 0x2f, 0x54,
	0x55, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x12, 0x17, 0x0f, 0x58, 0xc6, 0x31, 0x25, 0xa5,
	0x28, 0xb5, 0xb8, 0x18, 0xaa, 0x1a, 0x45, 0x4c, 0x49, 0x8d, 0x8b, 0x2f, 0x28, 0xb5, 0x2c, 0xb5,
	0xa8, 0x38, 0x15, 0xbf, 0xe1, 0xa6, 0x5c, 0xfc, 0x70, 0x75, 0xc4, 0x1b, 0x6f, 0x54, 0x0a, 0x35,
	0x4c, 0xc8, 0x88, 0x8b, 0x15, 0xec, 0x38, 0x21, 0x61, 0x88, 0xd7, 0xf4, 0x90, 0x3d, 0x24, 0x25,
	0x82, 0x2a, 0x08, 0xb5, 0xc0, 0x82, 0x8b, 0x1d, 0x6a, 0xa7, 0x90, 0x28, 0x54, 0x01, 0xaa, 0x5b,
	0xa5, 0xc4, 0xd0, 0x85, 0x21, 0x3a, 0x9d, 0x58, 0xa2, 0x98, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x92,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x5f, 0x09, 0x85, 0x53, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
	Reverse(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*ReverseResponse, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, "/proto.Email/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) Reverse(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*ReverseResponse, error) {
	out := new(ReverseResponse)
	err := c.cc.Invoke(ctx, "/proto.Email/Reverse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
type EmailServer interface {
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	Reverse(context.Context, *ReverseRequest) (*ReverseResponse, error)
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Email/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_Reverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Reverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Email/Reverse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Reverse(ctx, req.(*ReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _Email_Build_Handler,
		},
		{
			MethodName: "Reverse",
			Handler:    _Email_Reverse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
